easy_admin:
    site_name: 'Admin Panel'

    user:
        name_property_path: 'fullName'
        display_avatar: false

    #####################
    # Design
    #####################
    design:
        menu:
            - { entity: 'News', icon: 'newspaper-o' }
            - { entity: 'Settings', icon: 'wrench' }
            - { entity: 'Team', icon: 'users' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Careers', icon: 'id-badge' }
            - { entity: 'Post', icon: 'wordpress' }
            - { entity: 'Assets', icon: 'archive' }

        assets:
            js:
                - '/bundles/fosckeditor/adapters/jquery.js'
                - '/bundles/fosckeditor/ckeditor.js'

    #####################
    # List actions
    #####################
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '', title: 'Edit' }
            - { name: 'delete', icon: 'eraser', label: '', title: 'Delete' }
    entities:
        #####################
        # News
        #####################
        News:
            class: App\Entity\News
            form:
                fields:
                    - title
                    - author
                    - { property: 'content', type: 'fos_ckeditor', type_options: { config_name: 'view_textarea' } }
                    - { property: 'created_at', type: 'datetime' }

        #####################
        # Careers
        #####################
        Careers:
            class: App\Entity\Careers
            form:
                fields:
                    - jobtitle
                    - { property: 'requiments', type: 'textarea' }
                    - number

        #####################
        # Settings
        #####################
        Settings:
            class: App\Entity\Settings
            disabled_actions: ['new', 'delete', 'search']

        #####################
        # Team
        #####################
        Team:
            class: App\Entity\Team

        #####################
        # User
        #####################
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - full_name
                    - email
                    - { property: 'password', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        #####################
        # Post
        #####################
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - title
                    - summary
                    - { property: 'content', css_class: 'show-ckeditor', type: 'fos_ckeditor', type_options: { config_name: 'view_textarea' } }
                    - { property: 'published_at', type: 'datetime' }

        #####################
        # Assets
        #####################
        Assets:
            class: App\Entity\Assets
            form:
                fields:
                    - name
                    - sku
                    - { property: 'brand', type: 'choice', type_options: { multiple: true, choices:
                      {
                        'Daz': 'daz3d.com',
                        'Renderosity': 'renderosity.com'
                      }}}
                    - { property: 'description', css_class: 'show-ckeditor', type: 'fos_ckeditor', type_options: { config_name: 'view_textarea' } }
                    - website
                    - { property: 'hairtype', type: 'choice', type_options: { multiple: true, choices:
                      {
                          'Female': 'Female',
                          'Male': 'Male',
                          'Female and Male': 'Female and Male',
                          'Kids': 'Kids',
                          'Anime': 'Anime',
                          'Updo Hair': 'Updo Hair',
                          'Long Hair': 'Long Hair',
                          'Medium Hair': 'Medium Hair',
                          'Shoulder Length Hair': 'Shoulder Length Hair',
                          'Short Hair': 'Short Hair',
                          'Bob': 'Bob',
                          'Braid Hair': 'Braid Hair',
                          'Ponytail': 'Ponytail',
                          'Twintail (Pigtails)': 'Twintail (Pigtails)',
                          'Beard': 'Beard',
                          'Eyebrows': 'Eyebrows',
                          'Body Hair': 'Body Hair'
                      }}}
                    - { property: 'clothing', type: 'choice', type_options: { multiple: true, choices:
                      {
                        'Male': 'Male',
                        'Female': 'Female',
                        'Male and Female': 'Male and Female'
                      }}}
                    - { property: 'misc', type: 'choice', type_options: { multiple: true, choices:
                      {
                          'Animals': 'Animals',
                          'Animation': 'Animation',
                          'Brushes and Effects': 'Brushes and Effects',
                          'Buildings': 'Buildings',
                          'Creatures': 'Creatures',
                          'Footwear': 'Footwear',
                          'Headwear': 'Headwear',
                          'Jewelry': 'Jewelry',
                          'Lighs': 'Lighs',
                          'Natures': 'Natures',
                          'Plug-ins': 'Plug-ins',
                          'Poses': 'Poses',
                          'Props': 'Props',
                          'Shaders': 'Shaders',
                          'Shoes': 'Shoes',
                          'Softwares': 'Softwares',
                          'Structures': 'Structures',
                          'Tutorials': 'Tutorials'
                      }}}
                    - { property: 'requirement', type: 'choice', type_options: { multiple: true, choices: { 'HAIR': 'HAIR', 'OBJECT': 'OBJECTS' }}}
                    - { property: 'softwarecompatible', type: 'choice', type_options: { multiple: true, choices:
                      {
                          '3DS Max': '3DS Max',
                          'Bryce': 'Bryce',
                          'Carrara': 'Carrara',
                          'DAZ Studio': 'DAZ Studio',
                          'LightWave': 'LightWave',
                          'Maya': 'Maya',
                          'Poser': 'Poser',
                          'Unity': 'Unity',
                          'UnrealEngine': 'UnrealEngine',
                          'Vue': 'Vue'
                      }}}
                    - { property: 'figurecompatible', type: 'choice', type_options: { multiple: true, choices:
                      {
                        'Aiko 4 Base': 'Aiko 4 Base',
                        'Aiko 5': 'Aiko 5',
                        'David 3': 'David 3',
                        'David 5': 'David 5',
                        'David Base': 'David Base',
                        'Genesis': 'Genesis',
                        'Genesis 2 Female': 'Genesis 2 Female',
                        'Genesis 2 Male': 'Genesis 2 Male',
                        'Genesis 3 Female': 'Genesis 3 Female',
                        'Genesis 3 Male': 'Genesis 3 Male',
                        'Hiro 3': 'Hiro 3',
                        'Hiro 4 Base': 'Hiro 4 Base',
                        'Hiro 5': 'Hiro 5',
                        'Michael': 'Michael',
                        'Michael 2 & 1': 'Michael 2 & 1',
                        'Michael 3': 'Michael 3',
                        'Michael 4 Base': 'Michael 4 Base',
                        'Michael 4 Elite': 'Michael 4 Elite',
                        'Michael 5': 'Michael 5',
                        'Millennium Baby 3': 'Millennium Baby 3',
                        'Millennium Boy': 'Millennium Boy',
                        'Millennium Girl': 'Millennium Girl',
                        'Millennium Kids - Preschoolers': 'Millennium Kids - Preschoolers',
                        'Millennium Kids - Young Teens': 'Millennium Kids - Young Teens',
                        'Stephanie 4 Elite Base': 'Stephanie 4 Elite Base',
                        'Stephanie 5': 'Stephanie 5',
                        'The Freak 3': 'The Freak 3',
                        'The Freak 4 Base': 'The Freak 4 Base',
                        'The Freak 5': 'The Freak 5',
                        'the Girl 4 Base': 'the Girl 4 Base',
                        'The Kids 4': 'The Kids 4',
                        'Victoria 2 & 1': 'Victoria 2 & 1',
                        'Victoria 3': 'Victoria 3',
                        'Victoria 4': 'Victoria 4',
                        'Victoria 4.2': 'Victoria 4.2',
                        'Victoria 5': 'Victoria 5',
                        'Victoria 6': 'Victoria 6',
                        'Victoria 7': 'Victoria 7',
                        'Victoria 8': 'Victoria 8'
                      }}}
                    - { property: 'genre', type: 'choice', type_options: { multiple: true, choices:
                      {
                        'Contemporary': 'Contemporary',
                        'Fantasy': 'Fantasy',
                        'Toon': 'Toon',
                        'Historical': 'Historical',
                        'Anime': 'Anime',
                        'Sci-Fi': 'Sci-Fi',
                        'Gothic': 'Gothic',
                        'Eastern': 'Eastern',
                        'Steampunk / Victorian': 'Steampunk / Victorian',
                        'High Seas': 'High Seas',
                        'Horror': 'Horror',
                        'Egyptian': 'Egyptian'
                      }}}
                    - from
