framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            App\Message\CommandJobMessage: sync
            App\Message\RefreshStatsMessage: async
            App\Service\Import\Movie\MovieImportMessage: async
            App\Service\Import\Tv\TvImportMessage: async
            App\Service\Import\Season\SeasonImportMessage: async
            App\Service\Import\Episode\EpisodeImportMessage: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
