twig:
    globals:
        # Website name use eg: - or something else in front of name
        com_title:     - OktoDark
        # You can choose what theme to be for website:
        # default
        theme_site:    default

    debug:            '%kernel.debug%'
    strict_variables: ~
    paths:
              '%kernel.project_dir%/templates/default': theme
    auto_reload:      ~

