twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        # Website name use eg: - or something else in front of name
        com_title:     - OktoDark
        # You can choose what theme to be for website:
        # default
        theme_site:    default

