twig:
    auto_reload: true

    form_themes:
        - 'form/trix_editor_widget.html.twig'

    file_name_pattern: '*.twig'

    globals:
        social_icons: '%social_icons%'
        social_base_urls: '%social_base_urls%'
        social_colors: '%social_colors%'

when@test:
    twig:
        strict_variables: true
