twig:
    globals:
        # You can choose what theme to be for website:
        # default
        theme_site:    grey

    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates/grey': theme
    auto_reload:      ~

