language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    # - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=0

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: SYMFONY="5.0.*"
           ACTION="update"
    # 'php: nightly' is PHP 8.0
    - php: 7.4snapshot
  allow_failures:
    - php: 7.4snapshot

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - composer install
  # - ./bin/phpunit install

script:
# - ./bin/.phpunit
# - composer validate --strict