language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    # - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=9
    - ACTION="install"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: SYMFONY="5.0.*"
           ACTION="update"
    - php: 7.4

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4snapshot" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  # install or update
  - composer $ACTION
  # - ./bin/phpunit install

script:
# - ./bin/.phpunit
# - composer validate --strict