language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
      env: DB=mysqli
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  - composer install
  # - ./bin/phpunit install

script:
  - ./bin/.phpunit
  # - composer validate --strict